name: Maven Package

on:
  push: 
    branches: [ main ]
jobs:
  build:
    runs-on: spring
    steps:
    - name: Cloning Code
      uses: actions/checkout@v2
    - name: Building jar file
      run: |
        cd target
        screen java -jar *.jar
      
