name: Maven Package

on:
  push: 
    branches: [ main ]
jobs:
  build:
    runs-on: spring
    steps:
    - name: Cloning Code
      uses: actions/checkout@v2
    - name: Building jar file
      run: mvn clean install
    - name: Getting inside target folder and running jar file
      run: |
       cd target
       java -jar *.jar &
      
