name: Maven Package

on:
  push: 
    branches: [ main ]
jobs:
  build:
    runs-on: spring
    steps:
    - name: Cloning Code
      uses: actions/checkout@v2
    - name: Building jar file
      run: mvn package
    - name: Running the jar file
      run: |
        ls
        pwd
        cd target
        nohup java -jar *.jar &
      
